/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minijeu;

/**
 *
 * @author alize
 */
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;

public class FenetrePrincipale extends javax.swing.JFrame {

    /**
     * Creates new form FenetrePrincipale
     */
    GrilleDeCellule grille;
    int nbCoups;

    
    public FenetrePrincipale(int t) {
        initComponents();
        int TailleGrille=t;
        this.grille = new GrilleDeCellule(TailleGrille);
        initialiserPartie();
        

 PanneauGrille.setLayout(new GridLayout(TailleGrille, TailleGrille));
      for (int i = 0; i < TailleGrille; i++) {
        for (int j = 0; j < TailleGrille; j++) {
             CelluleLumineuseGraphique bouton_cellule = new CelluleLumineuseGraphique(i,j, this.grille.recupCellule(i, j)); // création d'un bouton
             PanneauGrille.add(bouton_cellule); // ajout au Jpanel PanneauGrille
            }
        }
 
  PanneauBoutonsVerticaux.setLayout(new GridLayout(TailleGrille, 1));
        // Configuration du panneau de boutons verticaux
            PanneauBoutonsVerticaux.setLayout(new GridLayout(TailleGrille, 1));
            for (int a = 0; a < TailleGrille; a++) {
                JButton bouton_ligne = new JButton("Ligne " + (a + 1));
                int ligne = a; // Variable nécessaire pour le listener
                bouton_ligne.addActionListener(e -> {
                    grille.activerLigneDeCellules(ligne); // Active une ligne de cellules
                    repaint(); // Met à jour l'affichage
                    verifierFinPartie();
                });
                PanneauBoutonsVerticaux.add(bouton_ligne); // Ajout du bouton au panneau
            }
       PanneauBoutonHorizontaux.setLayout(new GridLayout(1, TailleGrille));
            for (int b = 0; b < TailleGrille; b++) {
                JButton bouton_colonne = new JButton("Colonne " + (b + 1));
                int colonne = b; // Variable nécessaire pour le listener
                bouton_colonne.addActionListener(e -> {
                    grille.activerColonneDeCellules(colonne); // Active une colonne de cellules
                    repaint(); // Met à jour l'affichage
                    verifierFinPartie();
                });
                PanneauBoutonHorizontaux.add(bouton_colonne); // Ajout du bouton au panneau
            }
            PanneauBoutonHorizontaux.repaint();
            this.pack();
            this.revalidate();
        
        
 
     messageVictoire.setVisible(false); // Masqué au début
    
       
    }

    public void initialiserPartie() {
        grille.toutesCellulesEteintes();
        grille.melangerMatriceAleatoirement(10);
    }
       
  
// Méthode pour vérifier si la grille est éteinte et gérer la fin de partie
private void verifierFinPartie() {
    if (grille.toutesCellulesEteintes()) {
        messageVictoire.setText("Vous avez gagné!");
        messageVictoire.setVisible(true);
        desactiverBoutons(); // Désactiver tous les boutons
    }
    else {
        messageVictoire.setText(""); // Efface le message si la partie continue
    }
}

// Méthode pour désactiver les boutons une fois la partie terminée
private void desactiverBoutons() {
    btnDiagDescendante.setEnabled(false);
    btnDiagMontante.setEnabled(false);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        messageVictoire = new javax.swing.JTextField();
        PanneauBoutonsVerticaux = new javax.swing.JPanel();
        PanneauBoutonHorizontaux = new javax.swing.JPanel();
        btnDiagMontante = new javax.swing.JButton();
        btnDiagDescendante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 750, 430));

        messageVictoire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageVictoireActionPerformed(evt);
            }
        });
        getContentPane().add(messageVictoire, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 150, -1));

        PanneauBoutonsVerticaux.setLayout(new java.awt.GridLayout(0, 1));
        getContentPane().add(PanneauBoutonsVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, 430));

        PanneauBoutonHorizontaux.setLayout(new java.awt.GridLayout());
        getContentPane().add(PanneauBoutonHorizontaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 750, 40));

        btnDiagMontante.setText("DM");
        btnDiagMontante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagMontanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiagMontante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 60, 43));

        btnDiagDescendante.setText("DD");
        btnDiagDescendante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagDescendanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiagDescendante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 42));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiagDescendanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagDescendanteActionPerformed
        // TODO add your handling code here:
        this.grille.activerDiagonaleDescendante();
        repaint();
        verifierFinPartie();
    }//GEN-LAST:event_btnDiagDescendanteActionPerformed

    private void btnDiagMontanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagMontanteActionPerformed
        // TODO add your handling code here:
        this.grille.activerDiagonaleMontante();
        repaint();
        verifierFinPartie();
    }//GEN-LAST:event_btnDiagMontanteActionPerformed

    private void messageVictoireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageVictoireActionPerformed
        // TODO add your handling code here:
         this.verifierFinPartie();
        repaint();
        verifierFinPartie();
    }//GEN-LAST:event_messageVictoireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale(10).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauBoutonHorizontaux;
    private javax.swing.JPanel PanneauBoutonsVerticaux;
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JButton btnDiagDescendante;
    private javax.swing.JButton btnDiagMontante;
    private javax.swing.JTextField messageVictoire;
    // End of variables declaration//GEN-END:variables
}
